# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/crack_detect_usm_2024',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/crack_detect_usm_2024',
                'lib_path': 'crack_detect_usm_2024'},
  'syms': { 'crack_detect_usm_2024.core': {'crack_detect_usm_2024.core.foo': ('core.html#foo', 'crack_detect_usm_2024/core.py')},
            'crack_detect_usm_2024.preprocessing.cut_roi': { 'crack_detect_usm_2024.preprocessing.cut_roi.frm_full_img_to_splits': ( 'preprocess.cut_roi.html#frm_full_img_to_splits',
                                                                                                                                     'crack_detect_usm_2024/preprocessing/cut_roi.py'),
                                                             'crack_detect_usm_2024.preprocessing.cut_roi.frm_full_img_to_splits_folder': ( 'preprocess.cut_roi.html#frm_full_img_to_splits_folder',
                                                                                                                                            'crack_detect_usm_2024/preprocessing/cut_roi.py'),
                                                             'crack_detect_usm_2024.preprocessing.cut_roi.main_': ( 'preprocess.cut_roi.html#main_',
                                                                                                                    'crack_detect_usm_2024/preprocessing/cut_roi.py'),
                                                             'crack_detect_usm_2024.preprocessing.cut_roi.parse_args_': ( 'preprocess.cut_roi.html#parse_args_',
                                                                                                                          'crack_detect_usm_2024/preprocessing/cut_roi.py')}}}
