# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/crack_detect_usm_2024',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/crack_detect_usm_2024',
                'lib_path': 'crack_detect_usm_2024'},
  'syms': {'crack_detect_usm_2024.core': {'crack_detect_usm_2024.core.foo': ('core.html#foo', 'crack_detect_usm_2024/core.py')}}}
